# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-b
bind-key C-b send-prefix

set-window-option -g mode-keys vi
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#bind -T copy-mode-vi n send-keys -X next-prompt
#bind -T copy-mode-vi p send-keys -X previous-prompt

# copy like in vim
# https://superuser.com/questions/395158/tmux-copy-mode-select-text-block
# https://dev.to/iggredible/the-easy-way-to-copy-text-in-tmux-319g
bind -T copy-mode-vi v send -X begin-selection     # Begin selection in copy mode.
#bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind -T copy-mode-vi y send -X copy-selection      # Yank selection in copy mode.
#bind -T copy-mode-vi C-v send -X rectangle-toggle
#bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i'
bind P paste-buffer
#unbind-key -T copy-mode-vi v
set -s set-clipboard on

#set -g mouse on
set -g default-terminal "tmux-256color"

# List of plugins
#set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'azorng/tmux-smooth-scroll'
#
## Other examples:
## set -g @plugin 'github_username/plugin_name'
## set -g @plugin 'github_username/plugin_name#branch'
## set -g @plugin 'git@github.com:user/plugin'
## set -g @plugin 'git@bitbucket.com:user/plugin'
#set -g @plugin 'catppuccin/tmux'
#
#set -g @catppuccin_flavor "mocha"
#set -g @catppuccin_window_status_style "rounded"
#set -g status-right-length 100
#set -g status-left-length 100
#set -g status-left ""
#set -g status-right "#{E:@catppuccin_status_application}"
#set -agF status-right "#{E:@catppuccin_status_cpu}"
#set -ag status-right "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
#set -agF status-right "#{E:@catppuccin_status_battery}"
#
## Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run '~/.config/jordan_dotfiles/.tmux/plugins/tpm/tpm'
